<?php

namespace GaleriaBundle\Repository;

/**
 * AlquilerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlquilerRepository extends \Doctrine\ORM\EntityRepository
{
}
