<?php

namespace GaleriaBundle\Repository;

/**
 * NovedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NovedadesRepository extends \Doctrine\ORM\EntityRepository
{
}
